### ISSUE TITLE
Remove logging in/out in Translator

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-mongo#107]
https://github.com/lightblue-platform/lightblue-mongo/blob/42f88d2d45a83d096cc308dabc5b386053d90698/crud/src/main/java/com/redhat/lightblue/crud/mongo/Translator.java#L245

Data shouldn't be logged anywhere.

@bserdar is there a reason to keep this in?  Per git, you added this change about a week ago.

**Comment by dcrissman** [comment]
Ready for review

**Comment by bserdar** [comment]
These logs are valuable debugging tools. Instead of removing them, either:
  1) configure the logger so DEBUG level logs are written somewhere else, or
  2) we can use a separate logger for logs containing data

**Comment by dcrissman** [comment]
Closing per #123 109
