### ISSUE TITLE
Stop logging query in Translator

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-mongo#108]
https://github.com/lightblue-platform/lightblue-mongo/blob/42f88d2d45a83d096cc308dabc5b386053d90698/crud/src/main/java/com/redhat/lightblue/crud/mongo/Translator.java#L385

Similar to https://github.com/lightblue-platform/lightblue-mongo/issues/107 the query could have data in it we don't want to log in server.log.

**Comment by jewzaam** [comment]
And

https://github.com/lightblue-platform/lightblue-mongo/blob/42f88d2d45a83d096cc308dabc5b386053d90698/crud/src/main/java/com/redhat/lightblue/crud/mongo/Translator.java#L415

**Comment by dcrissman** [comment]
Ready for review
