### ISSUE TITLE
Exception when no version is provided.

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-mongo#122]
In the spirit of https://github.com/lightblue-platform/lightblue-rest/pull/153, I now get an exception from lightblue-mongo when a version is not provided.

https://github.com/lightblue-platform/lightblue-mongo/blob/master/metadata/src/main/java/com/redhat/lightblue/metadata/mongo/MongoMetadata.java#L88

**Comment by dcrissman** [comment]
@bserdar just wanted to bring this one to your attention.

**Comment by bserdar** [comment]
Note that it happens only if default version is not specified. If the
default version is not specified, and version is null, throwing an
exception is the correct response. Please check if your entityInfo has
defaultVersion field in it. If so, there is a bug. If not, then the
behavior is correct.

**Comment by dcrissman** [comment]
Confirmed, closing.
