### ISSUE TITLE
Mongodb hystrix group is ignored

### ISSUE THREAD

**Issue by paterczm** [lightblue-platform/lightblue-mongo#125]
Hystrix is ignoring configurations for mongodb group (confirmed this for coreSize and FindCommand).

I don't see anything wrong with how hystrix commands are initialized. FindCommand extends AbstractMongoCommand, which has mongodb group key hard coded. The [syntax used to pass group key is mentioned in hystrix javadocs](https://github.com/Netflix/Hystrix/blob/master/hystrix-core/src/main/java/com/netflix/hystrix/HystrixCommand.java#L152).

**Comment by bserdar** [comment]
https://github.com/lightblue-platform/lightblue-mongo/issues/254
