### ISSUE TITLE
Unable to delete existing index

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-mongo#147]
When I attempt to remove this index from existing metadata...

```json
{
                "name": null,
                "unique": true,
                "fields": [
                    {
                        "field": "_id",
                        "dir": "$asc"
                    }
                ]
            }
```

This error is returned.

```json
{"objectType":"error","context":"UpdateEntityInfoCommand/myEntity/updateEntityInfo(myEntity)","errorCode":"mongo-metadata:DatabaseError","msg":"{\"objectType\":\"error\",\"context\":\"UpdateEntityInfoCommand/myEntity/updateEntityInfo(myEntity)/createUpdateIndex\",\"errorCode\":\"mongo-crud:EntityIndexNotCreated\",\"msg\":\"{ \\\"serverUsed\\\" : \\\"my.mongo.host:port\\\" , \\\"nIndexesWas\\\" : 1 , \\\"ok\\\" : 0.0 , \\\"errmsg\\\" : \\\"cannot drop _id index\\\"}\"}"}
```

**Comment by bserdar** [comment]
That is the expected response. However, the real problem here is that there
are two _id indexes, one unique one not, and you can't remove either.

**Comment by dcrissman** [comment]
If an index on _id is implicit, should we throw an error if someone attempts to explicitly define it?

**Comment by bserdar** [comment]
No. The index is there, that's an accurate reflection of the back end. The
problem is the unique flag.

**Comment by bserdar** [comment]
This is still failing, even when there is only one _id index in both the
document and database copy of the entityInfo.

**Comment by bserdar** [comment]
It turns out, there is a *non-unique* id index in mongodb for
operationalProduct collection. That's why it's been complaining about it.
I'll fix the code to prevent this from happening. My guess is that the
broken metadata created two _id indexes, one unique one not, and then when
the metadata is fixed, the unique one is dropped, not the non-unique one,
and now since we have the unique index in metadata, it is trying to remove
the non-unique index, and create the unique index.

**Comment by bserdar** [comment]
Wrong diagnosis, mongo isn't letting this happen, continuing research....

**Comment by bserdar** [comment]
https://github.com/lightblue-platform/lightblue-mongo/pull/149

Please review and merge. It has two one-line fixes, and some unit tests.
Turned out to be a simple bug. While diagnosing also found an edge case in
translator.

This should be included in the next lightblue update.
