### ISSUE TITLE
Unique index on optional field doesn't work

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-mongo#156]
http://docs.mongodb.org/v2.6/core/index-unique/#unique-index-and-missing-field

```
If a document does not have a value for the indexed field in a unique index, the index will store a null value for this document. Because of the unique constraint, MongoDB will only permit one document that lacks the indexed field. If there is more than one document without a value for the indexed field or is missing the indexed field, the index build will fail with a duplicate key error.
```

This can be fixed for single field indexes by making the index `sparse`.

http://docs.mongodb.org/v2.6/core/index-sparse/

```
Sparse indexes only contain entries for documents that have the indexed field, even if the index field contains a null value. The index skips over any document that is missing the indexed field. The index is “sparse” because it does not include all documents of a collection. By contrast, non-sparse indexes contain all documents in a collection, storing null values for those documents that do not contain the indexed field.
```

Looks like it might even work for composite indexes:  http://docs.mongodb.org/v2.6/core/index-sparse/#sparse-compound-indexes

A few thoughts on this.  Index definitions in metadata are not mongo specific.  Sparse is a mongo concept.  There is a cost with sparse indexes, without a hint the index might not be used for some queries, such as $exists.  But lightblue doesn't have ability to map to an $exists mongo query.

Question:  Should we make all indexes in mongo sparse?

Marked as bug because in RDBMS world we expect the sparse behavior for even unique indexes.  A column being required is manged by table DDL (NOT NULL).

**Comment by bserdar** [comment]
Add properties support to index, and recognize "sparse" property in mongo
backend?

**Comment by jewzaam** [comment]
We'll go with making all unique indexes sparse.
Care must be taken with:
* index comparisons, do we compare all index options or just unique?
* _id index exclusion, don't mess it up.

Assuming we do not check for the sparse option in comparison we have a fall-back option of manually creating the unique index in mongo without sparse option set (if it mattered).
