### ISSUE TITLE
Ensure proper mongo tear down between tests

### ISSUE THREAD

**Issue by paterczm** [lightblue-platform/lightblue-mongo#174]
This is related to https://github.com/lightblue-platform/lightblue-mongo/pull/173. We wait 10s for mongo to tear down, otherwise data retains between tests, leading to weird failures. To save time, we should have a conditional wait which monitors mongo status.

**Comment by jewzaam** [comment]
Fixed with https://github.com/lightblue-platform/lightblue-mongo/pull/178
