### ISSUE TITLE
RFE: Bulk insert can be made faster

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-mongo#2]
<a href="https://github.com/bserdar"><img src="https://avatars.githubusercontent.com/u/3670797?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bserdar](https://github.com/bserdar)**
_Monday Apr 28, 2014 at 16:40 GMT_
_Originally opened as https://github.com/lightblue-platform/lightblue-core/issues/4_

----

We can group records that need to be inserted, and save them as batch. Possible problem: will we know which one failed if one of those fail?

**Comment by bserdar** [comment]
Included in https://github.com/lightblue-platform/lightblue-mongo/pull/259

**Comment by bserdar** [comment]
https://github.com/lightblue-platform/lightblue-mongo/pull/259
