### ISSUE TITLE
On Insert into an Array, null entries are excluded

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-mongo#215]
Say you wanted to create the following json array field [1], the insert request carries the correct data to lightblue, but the data is persisted without the null values [2]. This behaviour varies from an update's append, which will persist the null values exactly like what is expected [1].

[1]
```json
"street" : [
  "Address1",
  null,
  null,
  "Address4"
]
```

[2]
```json
"street" : [
  "Address1",
  "Address4"
]
```

**Comment by dcrissman** [comment]
Working on writing a unit test for this

**Comment by bserdar** [comment]
We decided to remove all null values a while ago.

**Comment by dcrissman** [comment]
Replaced by https://github.com/lightblue-platform/lightblue-core/issues/592
