### ISSUE TITLE
Expose read-preference to the client in execution options of the request

### ISSUE THREAD

**Issue by bserdar** [lightblue-platform/lightblue-mongo#216]

**Comment by jewzaam** [comment]
How is this going to be exposed to the client?  Will require changes to core and rest.  I also want to consider what we expose to clients, to both limit what they can do and to hide the mongoisms (naming).

For example, I see no reason to expose more than two options.
1. read=fast - translate to "nearest" in mongo controller
2. read=latest (or consistent or something else) - translate to "primaryPreferred" in mongo controller

I'd toss "primary" out completely, we should stop using it as it means reads are blocked if a new primary is being elected.  I don't see any value in the secondary options either.  If you need a secondary, it's probably so you can get to the nearest node.  If it is for another reason you probably have some specific workload to run and we need to look into tagging options.  Maybe a BI extract is one scenario.  Tossing it at any secondary will impact the production workloads on those secondaries.

**Comment by bserdar** [comment]
There is a pr in core that exposes this in execution options

**Comment by jewzaam** [comment]
Should the options for this be driven by the controller implementation?  I think it would be better to have something more generic that is implemented by each controller where the read preference is based on the behavior desired.

**Comment by bserdar** [comment]
Does having name-value pairs in execution options address this concern, or
do you have something else in mind?

**Comment by jewzaam** [comment]
From a schema point of view, having name value pairs address this.  But what I'm seeing is for me as a client I need to know the details of the mongo read preference options in order to override the default.  This means I need to know that the entity is stored in mongo.  What if we have an association between two backends?  How would a client specify a read preference if it's not generalized in core and translated to each backend?

**Comment by jewzaam** [comment]
Tracking discussion about translating the preference in https://github.com/lightblue-platform/lightblue-core/issues/606
