### ISSUE TITLE
Support limiting time query can run

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-mongo#219]
We've hit some cases where very long running queries impact lightblue either by taking db resources (maybe?) or crud resources (such as connections).

There are two options to mitigate this I'm seeing.
1) global config to force all queries to use indexes, [notablescan](https://docs.mongodb.org/v2.6/reference/parameters/#param.notablescan)
2) per-request limit max time a query can execute with [maxTimeMS](https://docs.mongodb.org/v2.6/reference/method/cursor.maxTimeMS/)

Would like to discuss (hopefully briefly) what other options exist and which one(s) should be adopted. 

I think the notablescan option is going to be a problem in that we cannot control what clients request from lightblue.  And it doesn't guarentee a long running query that does use an index won't be executed.

I think we should use maxTimeMS even if we set the timeout to something longer than other components in the architecture will timeout.  For example, if I query lightblue and a proxy times out after 30 seconds, the query will continue to run on the mongo server!  At least for find operations, this is a waste of resources.  We can debate if only find should be killed, but I think we should start there given it's the biggest problem we see so far.

My proposal, therefore, is:
* add support for already existing execution option: timeLimit
* add global default for timeLimit used if execution option is not specified
* in mongo controller use timeLimit as maxTimeMS

Looks like with the timeLimit in core we had this in mind.  It just didn't get implemented fully.

@BVulaj @bserdar @dcrissman @paterczm @snehagunta thoughts?

**Comment by dcrissman** [comment]
+1 maxTimeMS

**Comment by bserdar** [comment]
Timelimit is no longer an explicit execution option. Execution options are
name/value pairs, so we can make it an option.

The initial intend with timeLimit was to limit the time client waited on
query results. The plan was to continue running the query, and return a
future handle with which the client can come back and ask for results.
Never implemented.

Should we add timeLimit to the datasource, metadata, or both? Timelimit
specified in metadata would override timelimit specified in datasource.

Clients should be able to override timelimit, and should be able to specify
notimelimit.

With a default time limit, it is possible that under heavy load with an
unlucky query set, many clients timeout. Do we really want this?

**Comment by jewzaam** [comment]
I think at least a datasources (global) timeout with a execution option
override would be enough.  And we simply set the global limit to bigger
than the proxy timeout.  Then if the client times out talking to lightblue
the request is killed on the back-end.  With no async processing in place
there's no value in letting it run and it's actually bad to allow to
continue since it will take up resources.

I don't think per-metadata is necessary.  The per request would be for a
client that simply wants to get back stuff in a specific timeframe that's
shorter than global timeout at a proxy layer.
