### ISSUE TITLE
Updated document not set on save operations

### ISSUE THREAD

**Issue by alechenninger** [lightblue-platform/lightblue-mongo#230]
Tests show that updated document is not saved on the DocCtx for save operations. It only has original and output document.

I think this is a bug for two reasons:

1. Javadoc for DocCtx says that save and update should set this. Right now only update sets it in mongo controller.
2. If set, it would allow hooks to work with the unprojected result of a save operation. Currently hooks will only see the projected output of a save, which means to the hook, a projected save could look like fields were removed (again, if I understand correctly)

**Comment by bserdar** [comment]
Correct. saveOrInsert is setting only the outputDocument, not the
updatedDocument.  This should be done in the for-loop on saveOrInsert.

**Comment by alechenninger** [comment]
FWIW, it looks like my number 2 reason wasn't exactly correct: a doc context has four states, docRoot, originalDocument, updatedDocument, and outputDocument. The post doc of a hook will be docRoot or updatedDocument. In the case of the save operation, the docRoot is what was passed to the save, so we get the whole save entity data in the hook regardless of projections.

However, I think that still means that fields the saver does not have access to will not be shared to the hook, which might still cause problems. So I think in saveOrInsert once you have the merged dbObject we could set that as the updatedDocument and rejoice?

**Comment by bserdar** [comment]
As far as I can see, MongoCRUDController#186 is the place to do it; just
before projecting the doc, translate and set it as the updated doc.
