### ISSUE TITLE
Translator not handling nulls correctly

### ISSUE THREAD

**Issue by ykoer** [lightblue-platform/lightblue-mongo#236]
lightblue doesn't return any results if @nin has a null value and there is a reference projection. 

This is the query:
POST .../rest/data/find/subscription/0.0.1

`
{
     "projection": [
         {
             "field": "*",
             "include": true,
             "recursive": true
         },
         {
             "field": "legalEntity",
             "include": true,
             "recursive": true
         }
     ],
     "query": {
         "$and": [
             {
                 "array": "subscriptionProducts",
                 "elemMatch": {
                     "field": "status",
                     "op": "$nin",
                     "values": [
                         "Terminated",
                         null
                     ]
                 }
             },
             {
                 "field": "legalEntityId",
                 "op": "=",
                 "rvalue": 12345678
             },
             {
                 "$or": [
                     {
                         "field": "inactiveDate",
                         "op": "=",
                         "rvalue": null
                     },
                     {
                         "field": "inactiveDate",
                         "op": ">",
                         "rvalue": "20160406T23:59:59.999-0400"
                     }
                 ]
             },
             {
                 "array": "subscriptionProducts",
                 "elemMatch": {
                     "$or": [
                         {
                             "field": "inactiveDate",
                             "op": "=",
                             "rvalue": null
                         },
                         {
                             "field": "inactiveDate",
                             "op": ">",
                             "rvalue": "20160406T23:59:59.999-0400"
                         }
                     ]
                 }
             }
         ]
     },
     "sort": [
         {
             "_id": "$asc"
         },
         {
             "subscriptionProducts.uid": "$asc"
         }
     ]
}
`

**Comment by bserdar** [comment]
Fixed in core
