### ISSUE TITLE
Use update-if-current for find-then-replace operations

### ISSUE THREAD

**Issue by alechenninger** [lightblue-platform/lightblue-mongo#296]
If I understand correctly, it looks like updates do a find then replace on documents. I'm wondering if some inconsistencies can be explained with race conditions in this algorithm.

Imagine there are two (or more) updates for the same document in flight:

1. Request A finds document
2. Request B finds document
3. Request A updates document
4. Request B updates document, potentially overwriting result of request A, even though request B did not contain updates for overlapping fields

If all documents in mongo had an internal last update timestamp, could a query be added on this that would detect concurrent modifications? If detected, the process could be retried. We do this with many of our updates to lightblue, but I wonder now if that does not actually remove race conditions, since lightblue does not rewrite that to one mongo update (understandably, since this is not possible AFAIK with complex foreach update expressions and such).

Changing the algorithm would have other impacts I'm sure. For example, hooks would not be able to be fired in realtime, you might want to wait until you knew the operation was successful, then fire hooks.

Apologies if I am misunderstanding how the updates work.

**Comment by bserdar** [comment]
There is a race condition, we've had it from the beginning. It is unlikely
that this causes inconsistencies the way we use it, but possible. Also, the
race conditions in calling code is worse, and those are more likely to
cause inconsistencies.

Fixing this has been in my todo list for a while. Easiest solution is to
add a document version, increment it for every update, and fail the update
if the version changed during read/write. Retrying the update might not be
a safe option. Maybe it is time to give this more priority.

**Comment by alechenninger** [comment]
I think I found a case where I'm 90% sure this is what happened.

Thanks to the lightblue notification hook, I have a good understanding of events.

Here are notifications (except where noted) all for the same user. Let's call the field of interest "groups", an array of objects. Dates are from `hookDoc.getWhen()`.

1. 20160803T12:45:10.773-0400 - a group is added
2. 20160803T12:45:10.834-0400 - a different field is modified. However, the captured entity data, which always includes all group information, does _not_ include the group that was added in 1. I know what is in this request: it is an update which does _not_ modify groups.
3. 20160803T12:45:10.943-0400 - another group is added to the user. Still, the captured entity data does not include the group from 1.
4. Some other notifications happen here, same thing: the group from 1 is not there.
5. 2016-08-03 12:45:20,667 - An inconsistency is logged from a find service API which does not see group 1.
5. 20160803T12:47:19.728-0400 - migrator runs, adds back group 1.

I think the only explanation for that is that the update from 1 was blown away by the update in 2, but the update in 2 was for different fields; it would not have interacted with 1. So, I think it must have been in lightblue.

What do you think?

**Comment by dcrissman** [comment]
Change [1] was thrown away to be re-done. Moving out of the ready state.

[1] https://github.com/lightblue-platform/lightblue-mongo/pull/299
