### ISSUE TITLE
FORWARD_NULL in MongoCRUDController

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-mongo#310]
** CID 144030:  Null pointer dereferences  (FORWARD_NULL)
/lightblue-mongo/mongo/src/main/java/com/redhat/lightblue/mongo/crud/MongoCRUDController.java: 154 in com.redhat.lightblue.mongo.crud.MongoCRUDController.getOption(java.lang.String, java.lang.String)()

________________________________________________________________________________________________________
*** CID 144030:  Null pointer dereferences  (FORWARD_NULL)
/lightblue-mongo/mongo/src/main/java/com/redhat/lightblue/mongo/crud/MongoCRUDController.java: 154 in com.redhat.lightblue.mongo.crud.MongoCRUDController.getOption(java.lang.String, java.lang.String)()
148
149         private String getOption(String optionName,String defaultValue) {
150             if(controllerCfg!=null) {
151                 ObjectNode node=controllerCfg.getOptions();
152                 if(node!=null) {
153                     JsonNode value=node.get(optionName);
>>>     CID 144030:  Null pointer dereferences  (FORWARD_NULL)
>>>     Calling a method on null object "value".
154                     if(value!=null||!value.isNull())
155                         return value.asText();
156                 }
157             }
158             return defaultValue;
159         }

**Comment by bserdar** [comment]
Already fixed.
