### ISSUE TITLE
light blue mongo running with older version of lightblue core causing problem in building lightblue-metadata SNAPSHOT-2.14.0

### ISSUE THREAD

**Issue by JankiGadhiya** [lightblue-platform/lightblue-mongo#327]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project lightblue-rest-metadata: Compilation failure
[ERROR] /workspace/22ndOct/lightblue-master-repo/lightblue-master/lightblue-rest/metadata/src/main/java/com/redhat/lightblue/rest/metadata/cmd/ReIndexCommand.java:[46,20] cannot access com.redhat.lightblue.crud.ExplainQuerySupport
[ERROR] class file for com.redhat.lightblue.crud.ExplainQuerySupport not found

**Comment by bserdar** [comment]
There's nothing we can do about this. Use the latest. There is no established convention on version compatibility at this point.
