### ISSUE TITLE
Concurrent update retry update will never match a document

### ISSUE THREAD

**Issue by alechenninger** [lightblue-platform/lightblue-mongo#359]
We are seeing that when a concurrent update is detected, retries happen, but these retries never work, even if there is no other concurrent writes going on. We have reproduced this in tests, so we know there are no other concurrent writes.

I think the issue is here:

```
                    // Update the doc ver to our doc ver. This doc is here
                    // because its docVer is not set to our docver, so
                    // this is ok
                    DocVerUtil.setDocVer(newDoc,docVer);
                    // Using bulkwrite here with one doc to use the
                    // findAndReplace API, which is lacking in
                    // DBCollection
                    BulkWriteOperation nestedBwo=collection.initializeUnorderedBulkOperation();
                    nestedBwo.find(writeReplaceQuery(updatedDoc)).replaceOne(newDoc);
```

This writes the replace query after we have set the new doc version. This new query will never match, because that new doc version is of course not going to be the current; it's the new one in memory.

So writeReplaceQuery probably needs to run before setDocVer.

**Comment by bserdar** [comment]
Thanks for finding this, I knew there was something wrong with this
algorithm. I'll write a unit test and fix it.

**Comment by alechenninger** [comment]
Cool. At closer inspection, the docs are different, but updatedDoc and newDoc share a pointer to the same DBObject for the mongo hidden fields. So, setDocVer inadvertently updates both.

**Comment by bserdar** [comment]
Yes. Need a unit test to verify that's the case, once I have it, fixing is
easy.

**Comment by alechenninger** [comment]
Awesome, thank you!
