### ISSUE TITLE
Write concern needs to be configurable

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-mongo#48]
Right now we use SAFE which doesn't verify data is flushed to disk.  Two problems:
1. it's hard coded, we have no option for changing it in configuration
2. SAFE is probably not a great idea when we cannot afford to loose data

I propose we make it configurable in `datasources.json` per datasource and review what is the best for our deployment.  

http://api.mongodb.org/java/2.6/com/mongodb/WriteConcern.html

I say we configure for FSYNC_SAFE until we have a larger replica set.

**Comment by BVulaj** [comment]
Being developed in [48-write-concern](/BVulaj/lightblue-mongo/tree/48-write-concern).

**Comment by BVulaj** [comment]
Today, we hard-code WriteConcern.SAFE pretty much everywhere. Do we want to include refactoring that as part of this story?  As of now, MongoClient is now able to be configured via datasource.json.  See: development branch.

**Comment by jewzaam** [comment]
If you're talking within lightblue-mongo it would be preferred to have all hard coded use of a write concern updated, else the configuration option will be misleading (it exists but isn't really used).  Alternative is to get this change in as a PR and add another issue to update code to use it.

**Comment by bserdar** [comment]
Update the write concerns that deal with data and metadata only. In
particular, don't change the write concerns in locking.
