### ISSUE TITLE
Logical operators in queries in metadata cannot be saved to MongoDB

### ISSUE THREAD

**Issue by bserdar** [lightblue-platform/lightblue-mongo#55]
Metadata with query:[ "$and": [ ...] } causes this:

Document field names can't start with '$' (Bad Key: '$and')"

We have to save query/projection/sort as string.

**Comment by jewzaam** [comment]
Note: whatever is done here would need to be done for saved queries (if/when we do that feature: https://github.com/lightblue-platform/lightblue-core/issues/18).

**Comment by bserdar** [comment]
That means, saving the query/projection/sort as string.
