### ISSUE TITLE
Metadata creation should validate enum constraint against entityInfo

### ISSUE THREAD

**Issue by bserdar** [lightblue-platform/lightblue-mongo#69]
You can create metadata with an enum constraint on a field that is not defined in entityInfo.

**Comment by jewzaam** [comment]
Why is this a mongo thing?  What if the backend was changed for metadata?

**Comment by bserdar** [comment]
There is no default implementation of metadata creation in code.

The validation code is already there in code, EntityMetadata.validate(). It
just needs to be called before saving, and that's in mongo.

**Comment by bserdar** [comment]
Replaced some of the "code" with "core" in the last message to give it some meaning.

**Comment by bserdar** [comment]
EntityMetadata constructor calls validate(). I am removing that, it should
be validated before save/update, not right when it is constructed. During
construction, entity metadata can go through transient invalid states.

There is a bug in validate(), and when it is fixed, CompositeMetadata
construction fails because validate() is called during composite metadata
construction.
