### ISSUE TITLE
Empty array not persisted in document upon insertion

### ISSUE THREAD

**Issue by derek63** [lightblue-platform/lightblue-mongo#73]
If I insert a document with an empty array specified, the corresponding field is not persisted with the rest of the document.  The predefined field for the element count of the array is generated though

Example insert request
```
{
  "data": [
    {
      "_id": "testEntity_0",
      "objectType": "testEntity",
      "name": "testEntity",
      "arrayOfThings": [],
    }
  ],
  "projection": [
    {
      "field": "*",
      "include": true,
      "recursive": true
    }
  ]
}
```
Find response for that document
```
{
  "matchCount": 1,
  "modifiedCount": 0,
  "processed":
  [
    {
      "_id":"testEntity_0",
      "objectType": "testEntity",
      "name":"testEntity",
      "arrayOfThings#":0
    }
  ],
  "status":
  "COMPLETE"
}
```

**Comment by jewzaam** [comment]
I wondered, since I hadn't tried, if an empty array could be persisted.

```
> db.foo.insert({"name":"bob","stuff":[]});
WriteResult({ "nInserted" : 1 })
> db.foo.find()
{ "_id" : ObjectId("54dcf244447c64e738c8b2e6"), "name" : "bob", "stuff" : [ ] }
```

Looks like it is.

**Comment by jewzaam** [comment]
I'm curious about this one, going to take it on..

**Comment by bserdar** [comment]
Empty array can be persisted.

My guess is that the mongo translator class isn't translating the empty
array.

**Comment by jewzaam** [comment]
Yea, that's what it looks like.  I have a test for it, just trying to find time between meetings to dig into fixing it.  I suspect it won't be hard to fix.
