### ISSUE TITLE
Array $append and $insert not adding elements to existing array

### ISSUE THREAD

**Issue by derek63** [lightblue-platform/lightblue-mongo#74]
If I create an entity with a populated array field, and then attempt to add another object to it to it using $append, the addition is not persisted

Example insert request
```
{
  "data": [
    {
      "_id": "testEntity_0",
      "objectType": "testEntity",
      "name": "testEntity",
      "arrayOfThings": [ 
        {
          "name": "value"
        }
      ]
    }
  ],
  "projection": [
    {
      "field": "*",
      "include": true,
      "recursive": true
    }
  ]
}
```
I am submitting the following update statement to add another object to the array
```
{
  "query" : {
    "field":"_id","op":"$eq","rvalue":"testEntity_0"
  },
  "update" :  [
    {
      "$append" : {
        "arrayOfThings" : [
          {
            "name":"value2"
          }
        ]
      }
    }
  ],
  "projection": [
    {
      "field": "*",
      "include": true,
      "recursive": true
    }
  ]
}
```
And receive this response from the update statement (note the absence of the projected document)
```
{
  "status" : "COMPLETE",
  "modifiedCount" : 1,
  "matchCount" : 0
}
```
However when doing a find on that entity again, the new array object is not there
```
{
  "matchCount": 1,
  "modifiedCount": 0,
  "processed": [
    {
      "_id":"testEntity_0",
      "objectType": "testEntity",
      "name":"testEntity",
      "arrayOfThings": [
        {
          "name" : "value"
        }
      ],
      "arrayOfThings#":1
    }
  ],
  "status":
  "COMPLETE"
}
```

**Comment by derek63** [comment]
Note that $insert displays the same behavior with the following update query (whether I use 0 or 1 for the index)
```
{
  "query" : {
    "field":"_id","op":"$eq","rvalue":"testEntity_0"
  },
  "update" : {
    "$append" : {
      "arrayOfThings.1" : [
        {
          "name":"value2"
        }
      ]
      }
    },
    "projection": [
      {
        "field": "*",
        "include": true,
        "recursive": true
      }
    ]
}
```

**Comment by derek63** [comment]
Also note that the behavior is the same if I try to add an object to an array that was not pre-populated in the document (but is part of the entity metadata)

**Comment by bserdar** [comment]
This isn't a bug, but a feature.

I believe there is a ticket in core to address this idiosyncracy.

You can't add an initialized object element to an object array. You have to
add an empty element first, and then set the fields in it, So:

[ { "$append" : { "arrayOfThings" : {} } }, { "$set" : {
"arrayOfThings.-1.name":"value"} } ]


should work.


The reason for this is because the updater validates fields with
metadata. The $append updater
validates the array field, but does not recurse into the appended
values to see whether they match

the metadata or not.

**Comment by jewzaam** [comment]
Related issues:
* "It should be possible to update arrays with objects" https://github.com/lightblue-platform/lightblue-core/issues/180
* "There should be a way to save using a projection" https://github.com/lightblue-platform/lightblue-core/issues/184

**Comment by jewzaam** [comment]
@derek63 given the above limitation could you try this with an uninitialized object?

**Comment by jewzaam** [comment]
Pending testing by @derek63 today.

**Comment by luan-cestari** [comment]
@derek63  Hi, did you test it?

**Comment by derek63** [comment]
Sorry thought I had updated this already, $append-$set approach suggested by bserdar does work.
