### ISSUE TITLE
Update to treat any uid as an ObjectId?

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-mongo#77]
Right now the translator will only create an ObjectId if the field name is `_id`.  How about making this happen for a specific data type, such as uid?  This would mean deferring value generation to the backend.  Just was looking at the special handling for _id and thinking we could generalize things a bit.

**Comment by bserdar** [comment]
uid generation is done using Java uid apis. _id generation is done using
mongodb ObjectId apis.

**Comment by jewzaam** [comment]
Closing as field generation in core will be refactored to allow for more generic generation, beyond just uid supported today.  See https://github.com/lightblue-platform/lightblue-core/issues/204
